// Powered by OnSpace.AI

export const BUILD_STEPS = [
  { id: 'parse', label: 'Parsing prompt', detail: 'Analyzing requirements & intent...' },
  { id: 'design', label: 'Generating UI design', detail: 'Creating screens & components...' },
  { id: 'logic', label: 'Writing app logic', detail: 'Business logic & data flow...' },
  { id: 'assets', label: 'Generating assets', detail: 'Icons, images & animations...' },
  { id: 'compile', label: 'Compiling APK', detail: 'Building & packaging app...' },
  { id: 'sign', label: 'Signing & optimizing', detail: 'Finalizing installation package...' },
];

export const SAMPLE_PROMPTS = [
  'A habit tracker with streaks and daily reminders',
  'Restaurant menu app with online ordering',
  'Fitness workout timer with exercise library',
  'Personal finance tracker with charts',
  'Recipe app with ingredient scanner',
  'Language learning app with flashcards',
];

export const GALLERY_APPS = [
  {
    id: '1',
    name: 'FitTrack Pro',
    description: 'AI fitness tracker with workout plans and progress charts',
    prompt: 'A fitness app with workout tracking and AI coaching',
    category: 'Health',
    downloads: '12.4K',
    rating: 4.8,
    color: '#22C55E',
    buildTime: '47s',
    icon: 'fitness-center',
  },
  {
    id: '2',
    name: 'BudgetWise',
    description: 'Smart expense tracker with spending insights',
    prompt: 'Personal finance manager with budgets and charts',
    category: 'Finance',
    downloads: '8.9K',
    rating: 4.7,
    color: '#F59E0B',
    buildTime: '52s',
    icon: 'account-balance-wallet',
  },
  {
    id: '3',
    name: 'ChefAI',
    description: 'Recipe discovery app powered by AI ingredient detection',
    prompt: 'Recipe app with ingredient scanner and meal planning',
    category: 'Food',
    downloads: '15.2K',
    rating: 4.9,
    color: '#EF4444',
    buildTime: '38s',
    icon: 'restaurant',
  },
  {
    id: '4',
    name: 'MindfulMe',
    description: 'Meditation and mood tracking with guided sessions',
    prompt: 'Mental wellness app with meditation and mood journal',
    category: 'Wellness',
    downloads: '21.1K',
    rating: 4.9,
    color: '#7C3AED',
    buildTime: '41s',
    icon: 'self-improvement',
  },
  {
    id: '5',
    name: 'ShopLocal',
    description: 'Discover and support local businesses near you',
    prompt: 'App to find and support local small businesses',
    category: 'Shopping',
    downloads: '6.3K',
    rating: 4.6,
    color: '#4F8EF7',
    buildTime: '55s',
    icon: 'store',
  },
  {
    id: '6',
    name: 'LinguaFlow',
    description: 'Gamified language learning with AI conversation partner',
    prompt: 'Language learning app with daily challenges and AI chat',
    category: 'Education',
    downloads: '18.7K',
    rating: 4.8,
    color: '#00E5FF',
    buildTime: '49s',
    icon: 'translate',
  },
];
